- hosts: webservers
  gather_facts: no
  vars_files:
    - key.yml
  vars:
    UNIQUE_BUCKET_NAME: pola-the-savage
  tasks:
   - name: Create new S3 bucket
     aws_s3:
       aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
       aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
       bucket: "{{ UNIQUE_BUCKET_NAME }}"
       mode: create  
   - name: Add file to bucket
     aws_s3:    
       aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
       aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
       bucket: "{{ UNIQUE_BUCKET_NAME }}"
       object: pola.html
       src: /home/ec2-user/aws-tool/pola.html
       mode: put
       
