- hosts: webservers
  vars_files:
    - your-vars-file

  vars:
      region: # your-regiom
      instance_type: # instance type
      ami: # linux-2 ami image
      keypair: # pem file name
      subnetid:  # subnetid
      AWS_ACCESS_KEY_ID: # add-your-key
      AWS_SECRET_ACCESS_KEY: # add-your-key
  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         instance_type: "{{ instance_type }}"
         image: "{{ ami }}"
         aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
         aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: # provide a name for your count_tags
         instance_tags:
            Name: # provide a name for your instance_tag
         vpc_subnet_id: "{{ subnetid }}"
         assign_public_ip: yes
      register: ec2
