- hosts: webservers
  gather_facts: yes
  vars_files:
    - key.yml

  vars:
      region: us-east-1
      instance_type: t2.nano
      ami: ami-0a0ad6b70e61be944  # linux-2 ami image
      keypair: key-key # pem file name
      subnetid: subnet-57cad22d
      AWS_ACCESS_KEY_ID: # add-your-key
      AWS_SECRET_ACCESS_KEY: # add-your-key
  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         instance_type: "{{ instance_type }}"
         image: "{{ ami }}"
         aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
         aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: walid
         instance_tags:
            Name: kaku
         vpc_subnet_id: "{{ subnetid }}"
         assign_public_ip: yes
      register: ec2
