- hosts: webservers
  gather_facts: yes
  vars_files:
    - # --> add your var file here #
  tasks:
    - name: Create new IAM role
      iam_role:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}" # --> your vars file needs to contain this information #
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}" # --> your vars file needs to contain this information #
        ec2_region: "{{ AWS_REGION }}" # --> your vars file needs to contain this information #
        name: # --> provide a name #
        assume_role_policy_document: "{{ lookup('file','policy.json') }}" # --> this will point to your policy.json file #
        description: # --> add a description #
      register: iam_role
    - debug:
        var: iam_role
