- hosts: webservers
  gather_facts: no
  vars_files:
    - your-vars-file
  tasks:
    - name: Create new IAM user
      iam:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        iam_type: user
        state: present
        name:  #give username
        password: "{{ set_password }}" 
