- hosts: webservers
  gather_facts: yes
  vars_files:
    - your-var-file
  tasks:
    - name: Create new IAM role
      iam_role:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}" # will be included in your vars file
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}" # will be included in your vars file
        ec2_region: "{{ AWS_REGION }}" # will be included in your vars file
        name: # provide a name
        assume_role_policy_document: "{{ lookup('file','policy.json') }}" # this will point to your policy.json file
        description: # add a description
      register: iam_role
    - debug:
        var: iam_role
