- hosts: webservers
  gather_facts: yes
  vars_files:
    - your-vars-file
  tasks: 
    - name: Create new group with policy and add user
      iam_group:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        name: # provide a name
        managed_policy:
          - # add your policy here
        users:
          -  #user given above
        state: present
